# Generated by Django 6.1.1 on 2026-09-30 15:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_schoolclass'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdmissionApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('application_number', models.CharField(max_length=7, unique=True)),
                ('first_name', models.CharField(max_length=15)),
                ('last_name', models.CharField(max_length=15)),
                ('other_name', models.CharField(blank=True, max_length=15)),
                ('date_of_birth', models.DateField()),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=10)),
                ('address', models.CharField(max_length=50)),
                ('previous_school', models.CharField(max_length=30)),
                ('previous_class', models.CharField(max_length=10)),
                ('previous_result', models.FileField(upload_to='media/students/')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('under_review', 'Under Review'), ('approved', 'Approved'), ('not_admitted', 'Not Admitted'), ('enrolled', 'Enrolled')], default='pending', max_length=12)),
                ('passport', models.ImageField(upload_to='media/students/')),
                ('submitted_date', models.DateTimeField(auto_now_add=True)),
                ('reviewed_date', models.DateTimeField(blank=True, null=True)),
                ('class_applied_for', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounts.schoolclass')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounts.parent')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
